packages:
  - examples/**
  - playground
  - test/fixture
  - test/minimal

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - keytar
  - protobufjs
  - vue-demi

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - workerd

peerDependencyRules:
  ignoreMissing:
    - react
    - "@types/react"
    - react-dom
    - "@algolia/client-search"

shellEmulator: true
# Enable when https://github.com/pnpm/pnpm/pull/10168 lands
# trustPolicy: no-downgrade
# trustPolicyExclude:
#   - chokidar@4.0.3
