# https://pnpm.io/settings

shellEmulator: true
dedupePeers: true
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: "deep"

overrides:
  "nitro": "workspace:*"
  "cookie-es": "^3.1.1"
  "oxc-parser": "link:./shims/oxc-parser"
  # "vite": "^7"

packages:
  - examples/**
  - playground
  - test/fixture
  - test/minimal

trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@6.3.1"

blockExoticSubdeps: true
strictDepBuilds: true
allowBuilds:
  # Allowed
  "better-sqlite3": true
  # Blocked
  "@parcel/watcher": false
  "@prisma/client": false
  esbuild: false
  keytar: false
  sharp: false
  vue-demi: false
  workerd: false

peerDependencyRules:
  allowedVersions:
    vite: "8"
    typescript: "6"

updateConfig:
  ignoreDependencies:
    - vite7
