// Auto generated at 2025-10-05
// Source: https://platform-node-compat.deno.dev/
// Do not edit this file manually

// prettier-ignore
export const builtnNodeModules = [
  "node:_http_agent",
  "node:_http_common", // Missing exports: freeParser, isLenient, parsers, prepareError
  "node:_http_outgoing",
  "node:_http_server", // Missing exports: Server, ServerResponse, httpServerPreClose, kConnectionsCheckingInterval, kServerResponse, setupConnectionsTracking, storeHTTPOptions
  "node:_stream_duplex", // Missing exports: from, fromWeb, toWeb
  "node:_stream_passthrough",
  "node:_stream_readable", // Missing exports: ReadableState, from, fromWeb, toWeb, wrap
  "node:_stream_transform",
  "node:_stream_writable", // Missing exports: WritableState, fromWeb, toWeb
  "node:_tls_common", // Missing exports: SecureContext, translatePeerCertificate
  "node:_tls_wrap",
  "node:assert", // Missing exports: Assert, CallTracker, partialDeepStrictEqual
  "node:assert/strict", // Missing exports: Assert, CallTracker, partialDeepStrictEqual
  "node:async_hooks",
  "node:buffer", // Missing exports: File, resolveObjectURL
  "node:child_process",
  "node:cluster",
  "node:console", // Missing exports: context, createTask
  "node:constants", // Missing exports: O_DIRECT, O_NOATIME, defaultCipherList
  "node:crypto", // Missing exports: argon2, argon2Sync, decapsulate, encapsulate
  "node:dgram",
  "node:diagnostics_channel", // Missing exports: Channel
  "node:dns", // Missing exports: getDefaultResultOrder, lookupService, resolveTlsa
  "node:dns/promises", // Missing exports: getDefaultResultOrder, lookupService, resolveTlsa
  "node:domain",
  "node:events", // Missing exports: captureRejections, getMaxListeners, init, usingDomains
  "node:fs", // Missing exports: FileReadStream, FileWriteStream, Utf8Stream, fchmod, fchmodSync, fchown, fchownSync, glob, globSync, lchmod, lchmodSync, lchown, lchownSync, mkdtempDisposableSync, openAsBlob
  "node:fs/promises", // Missing exports: glob, lchmod, lchown, lutimes, mkdtempDisposable, statfs
  "node:http", // Missing exports: CloseEvent, MessageEvent, WebSocket, setMaxIdleHTTPParsers
  "node:http2", // Missing exports: performServerHandshake
  "node:https",
  "node:inspector", // Missing exports: NetworkResources
  "node:inspector/promises", // Missing exports: NetworkResources
  "node:module", // Missing exports: SourceMap, constants, enableCompileCache, findPackageJSON, flushCompileCache, getCompileCacheDir, getSourceMapsSupport, registerHooks, runMain, setSourceMapsSupport, stripTypeScriptTypes, syncBuiltinESMExports
  "node:net",
  "node:os",
  "node:path", // Missing exports: matchesGlob
  "node:path/posix", // Missing exports: matchesGlob
  "node:path/win32", // Missing exports: matchesGlob
  "node:perf_hooks", // Missing exports: Performance, PerformanceMark, PerformanceMeasure, PerformanceObserverEntryList, PerformanceResourceTiming, createHistogram
  "node:process", // Missing exports: availableMemory, binding, config, constrainedMemory, debugPort, domain, execve, exitCode, features, finalization, getActiveResourcesInfo, getgroups, hasUncaughtExceptionCaptureCallback, initgroups, loadEnvFile, moduleLoadList, openStdin, ppid, reallyExit, ref, release, report, resourceUsage, setSourceMapsEnabled, setUncaughtExceptionCaptureCallback, setegid, seteuid, setgid, setgroups, setuid, sourceMapsEnabled, threadCpuUsage, title, unref, uptime
  "node:punycode",
  "node:querystring",
  "node:readline",
  "node:readline/promises",
  "node:repl", // Missing exports: Recoverable, isValidSyntax, writer
  "node:sqlite", // Missing exports: Session, StatementSync, backup
  "node:stream", // Missing exports: destroy, promises
  "node:stream/consumers",
  "node:stream/promises",
  "node:stream/web",
  "node:string_decoder",
  "node:sys", // Missing exports: MIMEParams, MIMEType, diff, getCallSite, getSystemErrorMap, getSystemErrorMessage, parseEnv, setTraceSigInt, transferableAbortController, transferableAbortSignal
  "node:test", // Missing exports: assert, only, skip, snapshot, todo
  "node:timers",
  "node:timers/promises",
  "node:tls", // Missing exports: SecureContext, convertALPNProtocols, getCACertificates, setDefaultCACertificates
  "node:trace_events",
  "node:tty",
  "node:url", // Missing exports: URLPattern, fileURLToPathBuffer
  "node:util", // Missing exports: MIMEParams, MIMEType, diff, getCallSite, getSystemErrorMap, getSystemErrorMessage, parseEnv, setTraceSigInt, transferableAbortController, transferableAbortSignal
  "node:util/types", // Missing exports: isExternal
  "node:v8", // Missing exports: GCProfiler, getCppHeapStatistics, isStringOneByteRepresentation, promiseHooks, queryObjects, setHeapSnapshotNearHeapLimit, startupSnapshot
  "node:vm",
  "node:wasi",
  "node:worker_threads", // Missing exports: isInternalThread, isMarkedAsUntransferable, locks, markAsUncloneable, postMessageToThread, threadName
  "node:zlib", // Missing exports: ZstdCompress, ZstdDecompress, createZstdCompress, createZstdDecompress, zstdCompress, zstdCompressSync, zstdDecompress, zstdDecompressSync
];

// prettier-ignore
export const unsupportedNodeModules = [
  "node:_http_client",
  "node:_http_incoming",
  "node:_stream_wrap",
  "node:sea",
  "node:test/reporters",
];
