// Auto generated at 2025-10-05
// Source: https://platform-node-compat.pi0.workers.dev/
// Do not edit this file manually

// prettier-ignore
export const builtnNodeModules = [
  "node:_http_agent",
  "node:_http_client",
  "node:_http_common", // Missing exports: CRLF, HTTPParser, freeParser, isLenient, parsers, prepareError
  "node:_http_incoming", // Missing exports: readStart, readStop
  "node:_http_outgoing",
  "node:_http_server",
  "node:_stream_duplex",
  "node:_stream_passthrough",
  "node:_stream_readable",
  "node:_stream_transform",
  "node:_stream_writable",
  "node:_tls_common",
  "node:_tls_wrap", // Missing exports: Server, createServer
  "node:assert", // Missing exports: Assert, CallTracker
  "node:assert/strict", // Missing exports: Assert, CallTracker
  "node:async_hooks",
  "node:buffer",
  "node:constants", // Missing exports: O_DIRECT, O_NOATIME, RTLD_DEEPBIND, SIGPOLL, SIGPWR, SIGSTKFLT, defaultCipherList
  "node:crypto", // Missing exports: argon2, argon2Sync, decapsulate, encapsulate
  "node:diagnostics_channel",
  "node:dns", // Missing exports: resolveTlsa
  "node:dns/promises", // Missing exports: resolveTlsa
  "node:events", // Missing exports: captureRejections, init
  "node:fs", // Missing exports: Utf8Stream, mkdtempDisposableSync
  "node:fs/promises", // Missing exports: mkdtempDisposable
  "node:http",
  "node:http2",
  "node:https",
  "node:module",
  "node:net",
  "node:os",
  "node:path",
  "node:path/posix",
  "node:path/win32",
  "node:process",
  "node:querystring",
  "node:stream",
  "node:stream/consumers",
  "node:stream/promises",
  "node:stream/web",
  "node:string_decoder",
  "node:test", // Missing exports: after, afterEach, assert, before, beforeEach, describe, it, only, run, skip, snapshot, suite, test, todo
  "node:timers",
  "node:timers/promises",
  "node:tls", // Missing exports: getCACertificates, setDefaultCACertificates
  "node:url", // Missing exports: URLPattern, fileURLToPathBuffer
  "node:util", // Missing exports: diff, setTraceSigInt
  "node:util/types",
  "node:zlib", // Missing exports: ZstdCompress, ZstdDecompress, createZstdCompress, createZstdDecompress, zstdCompress, zstdCompressSync, zstdDecompress, zstdDecompressSync
];

// prettier-ignore
export const unsupportedNodeModules = [
  "node:_stream_wrap",
  "node:child_process",
  "node:cluster",
  "node:console",
  "node:dgram",
  "node:domain",
  "node:inspector",
  "node:inspector/promises",
  "node:perf_hooks",
  "node:punycode",
  "node:readline",
  "node:readline/promises",
  "node:repl",
  "node:sys",
  "node:trace_events",
  "node:tty",
  "node:v8",
  "node:vm",
  "node:wasi",
  "node:worker_threads",
  "node:sea",
  "node:sqlite",
  "node:test/reporters",
];
