import type { Middleware, ProxyOptions } from "h3";
import type { ExcludeFunctions, IntRange } from "./_utils.ts";
import type { CachedEventHandlerOptions } from "./runtime/index.ts";

export type HTTPstatus = IntRange<100, 600>;

export interface NitroRouteConfig {
  cache?: ExcludeFunctions<CachedEventHandlerOptions> | false;
  headers?: Record<string, string>;
  redirect?: string | { to: string; status?: HTTPstatus };
  prerender?: boolean;
  proxy?: string | ({ to: string } & ProxyOptions);
  isr?: number /* expiration */ | boolean | VercelISRConfig;

  // Shortcuts
  cors?: boolean;
  swr?: boolean | number;
  static?: boolean | number;
}

export interface NitroRouteRules extends Omit<
  NitroRouteConfig,
  "redirect" | "cors" | "swr" | "static"
> {
  redirect?: { to: string; status: HTTPstatus };
  proxy?: { to: string } & ProxyOptions;
  [key: string]: any;
}

export type MatchedRouteRule<K extends keyof NitroRouteRules = "custom"> = {
  name: K;
  options: Exclude<NitroRouteRules[K], false>;
  route: string;
  params?: Record<string, string>;
  handler?: (opts: unknown) => Middleware;
};

export type MatchedRouteRules = {
  [K in keyof NitroRouteRules]: MatchedRouteRule<K>;
};

// https://vercel.com/docs/build-output-api/primitives#prerender-configuration-file
export interface VercelISRConfig {
  /**
   * (vercel)
   * Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
   * Setting the value to `false` (or `isr: true` route rule) means it will never expire.
   */
  expiration?: number | false;

  /**
   * (vercel)
   * Group number of the asset.
   * Prerender assets with the same group number will all be re-validated at the same time.
   */
  group?: number;

  /**
   * (vercel)
   * List of query string parameter names that will be cached independently.
   * - If an empty array, query values are not considered for caching.
   * - If undefined each unique query value is cached independently
   * - For wildcard `/**` route rules, `url` is always added.
   */
  allowQuery?: string[];

  /**
   * (vercel)
   * When `true`, the query string will be present on the `request` argument passed to the invoked function. The `allowQuery` filter still applies.
   */
  passQuery?: boolean;

  /**
   * (vercel)
   *
   * When `true`, expose the response body regardless of status code including error status codes. (default `false`)
   */
  exposeErrBody?: boolean;
}
