import type { IntRange } from "./_utils.ts";

// Route rule types are owned by `h3-rules` (extracted from Nitro). Nitro
// re-exports them and augments the open `RouteRuleConfig` / `RouteRules`
// interfaces with its own rules (`isr`, `prerender`, `static`).
export type {
  RouteRuleConfig,
  RouteRules,
  MatchedRouteRule,
  MatchedRouteRules,
  RedirectRuleOptions,
  ProxyRuleOptions,
} from "h3-rules";

import type { RouteRuleConfig, RouteRules } from "h3-rules";

/**
 * @deprecated Use `RouteRuleConfig` from `h3-rules` (re-exported by `nitro/types`).
 */
export type NitroRouteConfig = RouteRuleConfig;

/**
 * @deprecated Use `RouteRules` from `h3-rules` (re-exported by `nitro/types`).
 */
export type NitroRouteRules = RouteRules;

/** Valid HTTP status code range (100–599). */
export type HTTPstatus = IntRange<100, 599>;

// --- Nitro-specific route rules (module augmentation) ---

// Augment the `h3-rules` config/rules interfaces so Nitro's own rules stay
// fully typed for users. `isr` / `prerender` / `static` are handled by Nitro
// (presets, prerenderer) rather than h3-rules runtime handlers.
declare module "h3-rules" {
  interface RouteRuleConfig {
    /**
     * Add this route to the prerender queue at build time.
     *
     * Only exact paths are collected; wildcard rules apply at runtime but are
     * not auto-added to the queue. Set to `false` to explicitly exclude a
     * route from prerendering.
     *
     * @see https://nitro.build/docs/routing#prerender
     */
    prerender?: boolean;

    /**
     * Incremental Static Regeneration on supported platforms.
     *
     * - `number` — revalidation time in seconds.
     * - `true` — never expires until the next deployment.
     * - `false` — disable ISR for this route.
     *
     * Only handled by presets with native support (e.g. Vercel, Netlify).
     * Ignored on platforms without ISR support.
     *
     * @see https://nitro.build/docs/routing#isr-vercel
     */
    isr?: number /* expiration */ | boolean | VercelISRConfig;

    static?: boolean | number;
  }

  interface RouteRules {
    prerender?: boolean;
    isr?: number | boolean | VercelISRConfig;
    static?: boolean | number;
  }
}

// https://vercel.com/docs/build-output-api/primitives#prerender-configuration-file
export interface VercelISRConfig {
  /**
   * (vercel)
   * Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
   * Setting the value to `false` (or `isr: true` route rule) means it will never expire.
   */
  expiration?: number | false;

  /**
   * (vercel)
   * Group number of the asset.
   * Prerender assets with the same group number will all be re-validated at the same time.
   */
  group?: number;

  /**
   * (vercel)
   * List of query string parameter names that will be cached independently.
   * - If an empty array, query values are not considered for caching.
   * - If undefined each unique query value is cached independently
   * - For wildcard `/**` route rules, `url` is always added.
   */
  allowQuery?: string[];

  /**
   * (vercel)
   * When `true`, the query string will be present on the `request` argument passed to the invoked function. The `allowQuery` filter still applies.
   */
  passQuery?: boolean;

  /**
   * (vercel)
   *
   * When `true`, expose the response body regardless of status code including error status codes. (default `false`)
   */
  exposeErrBody?: boolean;
}
