packages: []

shamefullyHoist: true

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  vue-demi: false


ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
