name: ci

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with: { node-version: lts/*, cache: pnpm }
      - run: pnpm install
      - run: pnpm stub && pnpm lint
  tests-checks:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with: { node-version: lts/*, cache: pnpm }
      - run: pnpm install
      - run: pnpm build
      - parallel:
          - run: pnpm typecheck
          - run: pnpm vitest run test/unit
          - run: pnpm vitest run test/minimal
          - run: pnpm vitest run test/vite
  tests-rollup:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest] # windows-latest disabled (flaky)

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with: { node-version: lts/*, cache: pnpm }
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        if: ${{ matrix.os != 'windows-latest' }}
        with: { bun-version: latest }
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        if: ${{ matrix.os != 'windows-latest' }}
        with: { deno-version: 2.9.6 }
      - run: node scripts/vite7.ts
      - run: pnpm install
      - run: pnpm build
      - parallel:
          - run: pnpm vitest run test/examples
            env: { NITRO_BUILDER: rollup, NITRO_VITE_PKG: vite7 }
          - run: pnpm vitest run test/presets
            env: { NITRO_BUILDER: rollup, NITRO_VITE_PKG: vite7 }

  tests-rolldown:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with: { node-version: lts/*, cache: pnpm }
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        if: ${{ matrix.os != 'windows-latest' }}
        with: { bun-version: latest }
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        if: ${{ matrix.os != 'windows-latest' }}
        with: { deno-version: 2.9.6 }
      - run: pnpm install
      - run: pnpm build
      - parallel:
          - run: pnpm vitest run test/examples
            env: { NITRO_BUILDER: rolldown, NITRO_VITE_PKG: vite }
          - run: pnpm vitest run test/presets
            env: { NITRO_BUILDER: rolldown, NITRO_VITE_PKG: vite }
  publish-pkg-pr-new:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [lint]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { fetch-depth: 0, persist-credentials: false }
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with: { node-version: lts/*, cache: "pnpm" }
      - run: pnpm install
      - run: pnpm build
      - run: pnpm dlx pkg-pr-new publish || true
  publish-nitro-nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: npm-publish-nightly
    permissions: { id-token: write, contents: read }
    needs: [tests-checks, tests-rollup, tests-rolldown]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && github.repository == 'nitrojs/nitro'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { fetch-depth: 0, persist-credentials: false }
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with: { node-version: lts/*, cache: "pnpm" }
      - run: pnpm install
      - run: pnpm build
      - run: pnpm changelogen --bump -r 3.0.1 --canary nightly
      - run: npm i -g npm@latest && npm publish --provenance --access public --tag latest
